workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Installer les dépendances
        script: |
          flutter pub get
      - name: Construire pour l'émulateur iOS
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
