platform :ios, '11.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunnerUITests' do
    # Pods for testing
  end
end
